steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/platform-images/governance-engine:$COMMIT_SHA'
      - './cloudrun'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/platform-images/governance-engine:$COMMIT_SHA'