name: Registry Sync

on:
  push:
    branches:
      - main
    paths:
      - "registry/**"

permissions:
  contents: read
  id-token: write

jobs:
  sync:

    runs-on: ubuntu-latest

    env:
      PROJECT_ID: platform-metadata-demo
      BUCKET: platform-metadata-demo-registry

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload Changed Registry Files
        shell: bash
        run: |

          echo "Finding changed registry files..."

          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^registry/applications/.*\.yaml$' || true)

          if [ -z "$FILES" ]; then
            echo "No registry files changed."
            exit 0
          fi

          echo "Uploading..."

          for file in $FILES
          do
            echo "Uploading $file"

            gcloud storage cp \
              "$file" \
              "gs://$BUCKET/applications/$(basename "$file")"

          done

          echo "Registry upload complete."
